name: release-and-publish

on:

  push:
    tags:
    - "v*.*.*"
   

jobs:
  create-release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      # - name: Check version is mentioned in Changelog
      #   uses: mindsers/changelog-reader-action@v2
      #   id: changelog
      #   with:
      #     validation_depth: 10
      #     path: CHANGELOG.md
      #
      # - name: Setup Go
      #   uses: actions/setup-go@v3
      #   with:
      #     go-version: '>=1.20.0'
      # 
      # - run: go version
      # 
      # - name: Build
      #   run: go build -o acli
      #

      - uses: softprops/action-gh-release@v1
        name: Create release
        with:
          token: ${{ github.token }}
          generate_release_notes: true
