name: release-and-publish

on:
 workflow_dispatch:
   

jobs:
  Create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check version is mentioned in Changelog
        uses: mindsers/changelog-reader-action@v2
        id: changelog
        with:
          validation_depth: 10
          path: CHANGELOG.md

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
      
      - run: go version
      
      - name: Build
        run: go build -o acli

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.changelog.outputs.version }}"
          name: "v${{ steps.changelog.outputs.version }}"
          body: ${{ steps.changelog.outputs.changes }}

