name: release-and-publish

on: 
  push:
    tags:
      - v*.*.*

jobs:
  create-release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
     
      - name: Set up Go
        uses: actions/setup-go@v4
      
      - name: Set version from main.go
        run: |
          version=$(cat main.go | awk -F'"' '/Version/ {print $2}')
          echo "Version: $version"
          echo "ACLI_VERSION=$version" >> $GITHUB_ENV

      - name: Make Release Dir
        run: mkdir bin
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.2

      # Check if the newest tag already exists
      - name: Check if tag exist
        uses: mukunku/tag-exists-action@9afafd1bf326f2957ca13d67122d44d5681e432b
        id: check-tag-exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{  github.ref_name }}
 
      # Build Binaries if this is a new release
      - name: Build ACLI Release Binaries
        run: make build-all
        if: ${{ steps.check-tag-exists.outputs.exists == 'false' }}
         
      # Create Release with artifacts
      - name: Create ACLI Release
        if: ${{ steps.check-tag-exists.outputs.exists == 'false'}}
        uses: softprops/action-gh-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          generate_release_notes: true
          files: |
            ./bin/*
